// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.4
// source: calculator/proto/calculator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculatorActions int32

const (
	CalculatorActions_UNDEFINED_ACTION CalculatorActions = 0
	CalculatorActions_ADD              CalculatorActions = 1
	CalculatorActions_MULTIPLY         CalculatorActions = 2
	CalculatorActions_CLEAR            CalculatorActions = 3
)

// Enum value maps for CalculatorActions.
var (
	CalculatorActions_name = map[int32]string{
		0: "UNDEFINED_ACTION",
		1: "ADD",
		2: "MULTIPLY",
		3: "CLEAR",
	}
	CalculatorActions_value = map[string]int32{
		"UNDEFINED_ACTION": 0,
		"ADD":              1,
		"MULTIPLY":         2,
		"CLEAR":            3,
	}
)

func (x CalculatorActions) Enum() *CalculatorActions {
	p := new(CalculatorActions)
	*p = x
	return p
}

func (x CalculatorActions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CalculatorActions) Descriptor() protoreflect.EnumDescriptor {
	return file_calculator_proto_calculator_proto_enumTypes[0].Descriptor()
}

func (CalculatorActions) Type() protoreflect.EnumType {
	return &file_calculator_proto_calculator_proto_enumTypes[0]
}

func (x CalculatorActions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CalculatorActions.Descriptor instead.
func (CalculatorActions) EnumDescriptor() ([]byte, []int) {
	return file_calculator_proto_calculator_proto_rawDescGZIP(), []int{0}
}

type CalculatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action CalculatorActions `protobuf:"varint,1,opt,name=action,proto3,enum=dummy.calculator.CalculatorActions" json:"action,omitempty"`
	Value  int64             `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CalculatorRequest) Reset() {
	*x = CalculatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_proto_calculator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatorRequest) ProtoMessage() {}

func (x *CalculatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_calculator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatorRequest.ProtoReflect.Descriptor instead.
func (*CalculatorRequest) Descriptor() ([]byte, []int) {
	return file_calculator_proto_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *CalculatorRequest) GetAction() CalculatorActions {
	if x != nil {
		return x.Action
	}
	return CalculatorActions_UNDEFINED_ACTION
}

func (x *CalculatorRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type CalculatorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultantValue int64 `protobuf:"varint,1,opt,name=resultantValue,proto3" json:"resultantValue,omitempty"`
}

func (x *CalculatorResponse) Reset() {
	*x = CalculatorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_proto_calculator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatorResponse) ProtoMessage() {}

func (x *CalculatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_calculator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatorResponse.ProtoReflect.Descriptor instead.
func (*CalculatorResponse) Descriptor() ([]byte, []int) {
	return file_calculator_proto_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *CalculatorResponse) GetResultantValue() int64 {
	if x != nil {
		return x.ResultantValue
	}
	return 0
}

type PrimeFactorizationRequeset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *PrimeFactorizationRequeset) Reset() {
	*x = PrimeFactorizationRequeset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_proto_calculator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeFactorizationRequeset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeFactorizationRequeset) ProtoMessage() {}

func (x *PrimeFactorizationRequeset) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_calculator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeFactorizationRequeset.ProtoReflect.Descriptor instead.
func (*PrimeFactorizationRequeset) Descriptor() ([]byte, []int) {
	return file_calculator_proto_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *PrimeFactorizationRequeset) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type PrimeFactorizationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Factor int32 `protobuf:"varint,1,opt,name=factor,proto3" json:"factor,omitempty"`
}

func (x *PrimeFactorizationResponse) Reset() {
	*x = PrimeFactorizationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_proto_calculator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeFactorizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeFactorizationResponse) ProtoMessage() {}

func (x *PrimeFactorizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_calculator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeFactorizationResponse.ProtoReflect.Descriptor instead.
func (*PrimeFactorizationResponse) Descriptor() ([]byte, []int) {
	return file_calculator_proto_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *PrimeFactorizationResponse) GetFactor() int32 {
	if x != nil {
		return x.Factor
	}
	return 0
}

var File_calculator_proto_calculator_proto protoreflect.FileDescriptor

var file_calculator_proto_calculator_proto_rawDesc = []byte{
	0x0a, 0x21, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x10, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x1a, 0x1e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a, 0x11, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x64, 0x75, 0x6d,
	0x6d, 0x79, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3c, 0x0a,
	0x12, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x34, 0x0a, 0x1a, 0x50,
	0x72, 0x69, 0x6d, 0x65, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x22, 0x34, 0x0a, 0x1a, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2a, 0x4b, 0x0a, 0x11, 0x43, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x10,
	0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x44, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4d,
	0x55, 0x4c, 0x54, 0x49, 0x50, 0x4c, 0x59, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x4c, 0x45,
	0x41, 0x52, 0x10, 0x03, 0x32, 0xbb, 0x02, 0x0a, 0x11, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x07, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x23, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2e, 0x63, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x64, 0x75, 0x6d,
	0x6d, 0x79, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x6e, 0x0a, 0x0e, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x69,
	0x7a, 0x65, 0x12, 0x2c, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x46, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x65, 0x74,
	0x1a, 0x2c, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01,
	0x12, 0x60, 0x0a, 0x07, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x12, 0x28, 0x2e, 0x64, 0x75,
	0x6d, 0x6d, 0x79, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2e, 0x63, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x28, 0x01, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x61, 0x6d, 0x6f, 0x67, 0x68, 0x32, 0x30, 0x31, 0x39, 0x2f, 0x64, 0x75, 0x6d, 0x6d, 0x79,
	0x5f, 0x67, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_calculator_proto_calculator_proto_rawDescOnce sync.Once
	file_calculator_proto_calculator_proto_rawDescData = file_calculator_proto_calculator_proto_rawDesc
)

func file_calculator_proto_calculator_proto_rawDescGZIP() []byte {
	file_calculator_proto_calculator_proto_rawDescOnce.Do(func() {
		file_calculator_proto_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(file_calculator_proto_calculator_proto_rawDescData)
	})
	return file_calculator_proto_calculator_proto_rawDescData
}

var file_calculator_proto_calculator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_calculator_proto_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_calculator_proto_calculator_proto_goTypes = []interface{}{
	(CalculatorActions)(0),             // 0: dummy.calculator.CalculatorActions
	(*CalculatorRequest)(nil),          // 1: dummy.calculator.CalculatorRequest
	(*CalculatorResponse)(nil),         // 2: dummy.calculator.CalculatorResponse
	(*PrimeFactorizationRequeset)(nil), // 3: dummy.calculator.PrimeFactorizationRequeset
	(*PrimeFactorizationResponse)(nil), // 4: dummy.calculator.PrimeFactorizationResponse
	(*AverageRequest)(nil),             // 5: dummy.calculator.request.AverageRequest
	(*AverageResponse)(nil),            // 6: dummy.calculator.request.AverageResponse
}
var file_calculator_proto_calculator_proto_depIdxs = []int32{
	0, // 0: dummy.calculator.CalculatorRequest.action:type_name -> dummy.calculator.CalculatorActions
	1, // 1: dummy.calculator.CalculatorService.operate:input_type -> dummy.calculator.CalculatorRequest
	3, // 2: dummy.calculator.CalculatorService.primeFactorize:input_type -> dummy.calculator.PrimeFactorizationRequeset
	5, // 3: dummy.calculator.CalculatorService.average:input_type -> dummy.calculator.request.AverageRequest
	2, // 4: dummy.calculator.CalculatorService.operate:output_type -> dummy.calculator.CalculatorResponse
	4, // 5: dummy.calculator.CalculatorService.primeFactorize:output_type -> dummy.calculator.PrimeFactorizationResponse
	6, // 6: dummy.calculator.CalculatorService.average:output_type -> dummy.calculator.request.AverageResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_calculator_proto_calculator_proto_init() }
func file_calculator_proto_calculator_proto_init() {
	if File_calculator_proto_calculator_proto != nil {
		return
	}
	file_calculator_proto_average_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_calculator_proto_calculator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculator_proto_calculator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculatorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculator_proto_calculator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeFactorizationRequeset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculator_proto_calculator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeFactorizationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_calculator_proto_calculator_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_proto_calculator_proto_goTypes,
		DependencyIndexes: file_calculator_proto_calculator_proto_depIdxs,
		EnumInfos:         file_calculator_proto_calculator_proto_enumTypes,
		MessageInfos:      file_calculator_proto_calculator_proto_msgTypes,
	}.Build()
	File_calculator_proto_calculator_proto = out.File
	file_calculator_proto_calculator_proto_rawDesc = nil
	file_calculator_proto_calculator_proto_goTypes = nil
	file_calculator_proto_calculator_proto_depIdxs = nil
}
