// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.4
// source: calculator/proto/max_among_all.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MaxAmongAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *MaxAmongAllRequest) Reset() {
	*x = MaxAmongAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_proto_max_among_all_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxAmongAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxAmongAllRequest) ProtoMessage() {}

func (x *MaxAmongAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_max_among_all_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxAmongAllRequest.ProtoReflect.Descriptor instead.
func (*MaxAmongAllRequest) Descriptor() ([]byte, []int) {
	return file_calculator_proto_max_among_all_proto_rawDescGZIP(), []int{0}
}

func (x *MaxAmongAllRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type MaxAmongAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxNum int64 `protobuf:"varint,1,opt,name=maxNum,proto3" json:"maxNum,omitempty"`
}

func (x *MaxAmongAllResponse) Reset() {
	*x = MaxAmongAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_proto_max_among_all_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxAmongAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxAmongAllResponse) ProtoMessage() {}

func (x *MaxAmongAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_max_among_all_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxAmongAllResponse.ProtoReflect.Descriptor instead.
func (*MaxAmongAllResponse) Descriptor() ([]byte, []int) {
	return file_calculator_proto_max_among_all_proto_rawDescGZIP(), []int{1}
}

func (x *MaxAmongAllResponse) GetMaxNum() int64 {
	if x != nil {
		return x.MaxNum
	}
	return 0
}

var File_calculator_proto_max_among_all_proto protoreflect.FileDescriptor

var file_calculator_proto_max_among_all_proto_rawDesc = []byte{
	0x0a, 0x24, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x78, 0x5f, 0x61, 0x6d, 0x6f, 0x6e, 0x67, 0x5f, 0x61, 0x6c, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2e, 0x63, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x2c, 0x0a, 0x12, 0x4d, 0x61, 0x78, 0x41,
	0x6d, 0x6f, 0x6e, 0x67, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2d, 0x0a, 0x13, 0x4d, 0x61, 0x78, 0x41, 0x6d, 0x6f,
	0x6e, 0x67, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x61, 0x78, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d,
	0x61, 0x78, 0x4e, 0x75, 0x6d, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6d, 0x6f, 0x67, 0x68, 0x32, 0x30, 0x31, 0x39, 0x2f, 0x64, 0x75,
	0x6d, 0x6d, 0x79, 0x5f, 0x67, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_calculator_proto_max_among_all_proto_rawDescOnce sync.Once
	file_calculator_proto_max_among_all_proto_rawDescData = file_calculator_proto_max_among_all_proto_rawDesc
)

func file_calculator_proto_max_among_all_proto_rawDescGZIP() []byte {
	file_calculator_proto_max_among_all_proto_rawDescOnce.Do(func() {
		file_calculator_proto_max_among_all_proto_rawDescData = protoimpl.X.CompressGZIP(file_calculator_proto_max_among_all_proto_rawDescData)
	})
	return file_calculator_proto_max_among_all_proto_rawDescData
}

var file_calculator_proto_max_among_all_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_calculator_proto_max_among_all_proto_goTypes = []interface{}{
	(*MaxAmongAllRequest)(nil),  // 0: dummy.calculator.MaxAmongAllRequest
	(*MaxAmongAllResponse)(nil), // 1: dummy.calculator.MaxAmongAllResponse
}
var file_calculator_proto_max_among_all_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calculator_proto_max_among_all_proto_init() }
func file_calculator_proto_max_among_all_proto_init() {
	if File_calculator_proto_max_among_all_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_calculator_proto_max_among_all_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaxAmongAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculator_proto_max_among_all_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaxAmongAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_calculator_proto_max_among_all_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_calculator_proto_max_among_all_proto_goTypes,
		DependencyIndexes: file_calculator_proto_max_among_all_proto_depIdxs,
		MessageInfos:      file_calculator_proto_max_among_all_proto_msgTypes,
	}.Build()
	File_calculator_proto_max_among_all_proto = out.File
	file_calculator_proto_max_among_all_proto_rawDesc = nil
	file_calculator_proto_max_among_all_proto_goTypes = nil
	file_calculator_proto_max_among_all_proto_depIdxs = nil
}
