// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.4
// source: sampleMap.proto

package level3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CityList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cities []string `protobuf:"bytes,1,rep,name=cities,proto3" json:"cities,omitempty"`
}

func (x *CityList) Reset() {
	*x = CityList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sampleMap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CityList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityList) ProtoMessage() {}

func (x *CityList) ProtoReflect() protoreflect.Message {
	mi := &file_sampleMap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityList.ProtoReflect.Descriptor instead.
func (*CityList) Descriptor() ([]byte, []int) {
	return file_sampleMap_proto_rawDescGZIP(), []int{0}
}

func (x *CityList) GetCities() []string {
	if x != nil {
		return x.Cities
	}
	return nil
}

type Country struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateWiseCityList map[string]*CityList `protobuf:"bytes,1,rep,name=stateWiseCityList,proto3" json:"stateWiseCityList,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Country) Reset() {
	*x = Country{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sampleMap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Country) ProtoMessage() {}

func (x *Country) ProtoReflect() protoreflect.Message {
	mi := &file_sampleMap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Country.ProtoReflect.Descriptor instead.
func (*Country) Descriptor() ([]byte, []int) {
	return file_sampleMap_proto_rawDescGZIP(), []int{1}
}

func (x *Country) GetStateWiseCityList() map[string]*CityList {
	if x != nil {
		return x.StateWiseCityList
	}
	return nil
}

var File_sampleMap_proto protoreflect.FileDescriptor

var file_sampleMap_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x15, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x63,
	0x65, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x33, 0x22, 0x22, 0x0a, 0x08, 0x43, 0x69, 0x74, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x63, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0xd5, 0x01, 0x0a,
	0x07, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x63, 0x0a, 0x11, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x57, 0x69, 0x73, 0x65, 0x43, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x61, 0x63,
	0x74, 0x69, 0x63, 0x65, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x33, 0x2e, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x57, 0x69, 0x73, 0x65, 0x43, 0x69, 0x74,
	0x79, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x11, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x57, 0x69, 0x73, 0x65, 0x43, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x65, 0x0a,
	0x16, 0x53, 0x74, 0x61, 0x74, 0x65, 0x57, 0x69, 0x73, 0x65, 0x43, 0x69, 0x74, 0x79, 0x4c, 0x69,
	0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x35, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74,
	0x2e, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x63, 0x65, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x33,
	0x2e, 0x43, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x61, 0x6d, 0x6f, 0x67, 0x68, 0x32, 0x30, 0x31, 0x39, 0x2f, 0x64, 0x75, 0x6d,
	0x6d, 0x79, 0x5f, 0x67, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x72,
	0x65, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69,
	0x63, 0x65, 0x2f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x33, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_sampleMap_proto_rawDescOnce sync.Once
	file_sampleMap_proto_rawDescData = file_sampleMap_proto_rawDesc
)

func file_sampleMap_proto_rawDescGZIP() []byte {
	file_sampleMap_proto_rawDescOnce.Do(func() {
		file_sampleMap_proto_rawDescData = protoimpl.X.CompressGZIP(file_sampleMap_proto_rawDescData)
	})
	return file_sampleMap_proto_rawDescData
}

var file_sampleMap_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sampleMap_proto_goTypes = []interface{}{
	(*CityList)(nil), // 0: greet.practice.level3.CityList
	(*Country)(nil),  // 1: greet.practice.level3.Country
	nil,              // 2: greet.practice.level3.Country.StateWiseCityListEntry
}
var file_sampleMap_proto_depIdxs = []int32{
	2, // 0: greet.practice.level3.Country.stateWiseCityList:type_name -> greet.practice.level3.Country.StateWiseCityListEntry
	0, // 1: greet.practice.level3.Country.StateWiseCityListEntry.value:type_name -> greet.practice.level3.CityList
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sampleMap_proto_init() }
func file_sampleMap_proto_init() {
	if File_sampleMap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sampleMap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CityList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sampleMap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Country); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sampleMap_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sampleMap_proto_goTypes,
		DependencyIndexes: file_sampleMap_proto_depIdxs,
		MessageInfos:      file_sampleMap_proto_msgTypes,
	}.Build()
	File_sampleMap_proto = out.File
	file_sampleMap_proto_rawDesc = nil
	file_sampleMap_proto_goTypes = nil
	file_sampleMap_proto_depIdxs = nil
}
